### ISSUE TITLE
Can't figure out where to download data

### ISSUE THREAD

**Issue by csu** [ilbonte/rescuetime-again#1]
The README says:

> On the main page you can choose to download the data for the selected range

But I can't find anything in the RescueTime UI to download my data. Where is this supposed to be?

**Comment by csu** [comment]
Ah, it looks like csv export is Premium only.

**Comment by csu** [comment]
So I got the csv, put it into the merge page, got out the JSON, and uploaded the JSON, but now I don't see anything:

![image](https://cloud.githubusercontent.com/assets/164822/11547981/0461ed42-990d-11e5-8e4e-6dff175e3120.png)

How exactly does this work? Do the JSON files include all the csv files uploaded? Or is there a separate JSON file for each csv file? Am I supposed to press "Elaborate" for every single JSON file?

**Comment by ilbonte** [comment]
You are supposed to download the JSON from the project page not from RescueTIme's website. This is because the structure may be different and so it can't be recognized.
Just insert your api key, select a range (i suggest at least a week), check the check-box press "elaborate" and the download should start automatically. If not you can click the download link.
![screenshot from 2015-12-03 09 15 31](https://cloud.githubusercontent.com/assets/7412876/11555223/f533d424-999e-11e5-87e1-f1a07a1a7678.png)
