### ISSUE TITLE
Dynamic?

### ISSUE THREAD

**Issue by arjunmayilvaganan** [ilbonte/rescuetime-again#7]
Does the graph values change dynamically without refreshing (/`Elaborate`)?

**Comment by ilbonte** [comment]
No. You need to press the button
RescueTime upload the data from your computer to their servers every 30 mins or every 5 mins if you are using the premium version.
By the way I'm thinking to do a complete code refactor in the next week (and drop google chart for highcharts or some other framework).
I might add this feature, but for now I don't thinks it's very useful because this tool is intended for and analysis of at least one week of data.
